CREATE SEQUENCE BOOK_ID_CATEGORY_SEQ start with 1 increment by 1 /
CREATE TABLE BOOK_CATEGORIES(
        ID INTEGER NOT NULL ,
        NAME VARCHAR(20) not null ,
        DESCRIPTION VARCHAR2(1000),
        PARENT_ID INTEGER,
        CONSTRAINT ID_PK PRIMARY KEY (ID)) /
CREATE OR REPLACE TRIGGER BOOK_CATEGORIES_TR BEFORE INSERT ON BOOK_CATEGORIES FOR EACH ROW
    BEGIN
        SELECT BOOK_ID_CATEGORY_SEQ.nextval INTO :new.id FROM dual;
    END; /

CREATE SEQUENCE BOOK_ID_PRODUCT_SEQ start with 1 increment by 1 /
CREATE TABLE BOOK_PRODUCT(
        ID INTEGER NOT NULL,
        NAME VARCHAR(20) not null,
        DESCRIPTION VARCHAR2(1000),
        PRICE FLOAT(126),
        IS_ACTIVE BIT,
        CONSTRAINT ID_PK PRIMARY KEY (ID)) /
CREATE OR REPLACE TRIGGER BOOK_TR_CATEGORIES BEFORE INSERT ON BOOK_CATEGORIES
    FOR EACH ROW
    BEGIN
        SELECT BOOK_ID_PRODUCT_SEQ.nextval INTO :new.id FROM dual;
    END; /